{{- if .Values.azureSecrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "fdc-dotnetcore-app.fullname" . }}-secrets
  labels:
    {{- include "fdc-dotnetcore-app.labels" . | nindent 4 }}
spec:
  provider: azure
  # the secret will be auto-created when there is any pod mounted that would need this secret and auto deleted when there are no pods referring to it
  secretObjects:
    - secretName: {{ include "fdc-dotnetcore-app.fullname" . }}-secret
      annotations:
        reloader.stakater.com/match: "true"
      type: Opaque
      {{- with .Values.azureSecrets.secrets }}
      data:
      {{- range $key, $value := . }}
        - objectName: {{ $value }}
          key: {{ $key }}
      {{- end }}
      {{- end }}
  parameters:
    usePodIdentity: {{ .Values.azureSecrets.usePodIdentity }}
    useVMManagedIdentity: {{ .Values.azureSecrets.useVMManagedIdentity }}
    userAssignedIdentityID: {{ .Values.azureSecrets.userAssignedIdentityId }}
    keyvaultName: {{ .Values.azureSecrets.keyvaultName }}
    cloudName: {{ .Values.azureSecrets.cloudName }}
    {{- with .Values.azureSecrets.secrets }}
    objects: |
      array:
      {{- range $key, $value := . }}
        - |
          objectName: {{ $value }}
          objectType: secret
          objectVersion: "" 
      {{- end }}
    {{- end }}
    tenantId: {{ .Values.azureSecrets.tenantId }}
{{- end }}