apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "fdc-dotnetcore-app.labels" . | nindent 4 }}
data:
  {{- range .Values.env }}
  {{ .name }}: "{{ .value }}"
  {{- end }}
 
